"""
Generate a publication-style SR comparison figure.

Layout:
  Left  : full original image with a red rectangle marking the crop region
  Right : cropped patches side by side (GT, Bicubic, Baseline, Ours)
           each labelled with model name and PSNR / SSIM
  Lines : two red lines connecting the rectangle corners to the first crop panel

Requires:
  comparisons/<image>/original.png
  comparisons/<image>/cropped/*.png   (generated by test.py --crop)
  comparisons/<image>/crop.json
  comparisons/<image>/metrics.csv

Usage:
  python make_figure.py --folder comparisons/butterfly/x3
  python make_figure.py --folder comparisons/cartoon/x3
"""

import argparse
import csv
import json
import os

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from matplotlib.patches import ConnectionPatch
import numpy as np
from PIL import Image


# Human-readable labels for known run names
LABEL_MAP = {
    'original':                    'Ground Truth',
    'x2_bicubic':                  'Bicubic ×2',
    'x3_bicubic':                  'Bicubic ×3',
    'x4_bicubic':                  'Bicubic ×4',
    'x2_mse_noaug_nosched_nores':  'Baseline',
    'x3_mse_noaug_nosched_nores':  'Baseline',
    'x4_mse_noaug_nosched_nores':  'Baseline',
    'x2_l1':                       'SRCNN+ (L1)',
    'x3_l1':                       'SRCNN+ (L1)',
    'x4_l1':                       'SRCNN+ (L1)',
    'x2_mse':                      'SRCNN+ (MSE)',
    'x3_mse':                      'SRCNN+ (MSE)',
    'x4_mse':                      'SRCNN+ (MSE)',
}


def load_metrics(folder):
    """Return dict of {model_name: (psnr, ssim)} from x{scale}_metrics.csv."""
    metrics = {}
    for f in os.listdir(folder):
        if f.endswith('_metrics.csv'):
            with open(os.path.join(folder, f), newline='') as fh:
                for row in csv.DictReader(fh):
                    metrics[row['model']] = (float(row['psnr_db']), float(row['ssim']))
    return metrics


def stem(filename):
    return os.path.splitext(filename)[0]


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--folder', type=str, required=True,
                        help='Scale folder, e.g. comparisons/butterfly/x3')
    parser.add_argument('--dpi', type=int, default=150)
    args = parser.parse_args()

    folder = args.folder.rstrip('/\\')
    scale_name = os.path.basename(folder)           # e.g. "x3"
    image_name = os.path.basename(os.path.dirname(folder))  # e.g. "butterfly"

    # Paths
    original_path = os.path.join(folder, 'original.png')
    crop_json     = os.path.join(os.path.dirname(folder), 'crop.json')
    cropped_dir   = os.path.join(folder, 'cropped')

    if not os.path.exists(original_path):
        raise FileNotFoundError('original.png not found in {}'.format(folder))
    if not os.path.exists(crop_json):
        raise FileNotFoundError('crop.json not found — run test.py --crop first')
    if not os.path.exists(cropped_dir):
        raise FileNotFoundError('cropped/ folder not found — run test.py --crop first')

    with open(crop_json) as f:
        crop = tuple(json.load(f))

    metrics = load_metrics(folder)

    # Collect cropped panels in display order: original, bicubic, baseline, Ours
    ORDER = ['original', 'x2_bicubic', 'x3_bicubic', 'x4_bicubic',
             'x2_mse_noaug_nosched_nores', 'x3_mse_noaug_nosched_nores', 'x4_mse_noaug_nosched_nores',
             'x2_l1', 'x3_l1', 'x4_l1', 'x2_mse', 'x3_mse', 'x4_mse']

    available = {stem(f): os.path.join(cropped_dir, f)
                 for f in os.listdir(cropped_dir) if f.endswith('.png')}

    panels = [(s, available[s]) for s in ORDER if s in available]
    # Append any remaining panels not in ORDER
    for s, p in available.items():
        if s not in [x[0] for x in panels]:
            panels.append((s, p))

    n_panels = len(panels)
    if n_panels == 0:
        raise RuntimeError('No cropped images found in {}'.format(cropped_dir))

    # Figure layout: 1 row, (1 full image + n_panels crops)
    # Full image column is wider
    full_img = np.array(Image.open(original_path))
    h, w = full_img.shape[:2]
    crop_w = crop[2] - crop[0]
    crop_h = crop[3] - crop[1]
    aspect_full  = w / h
    aspect_crop  = crop_w / crop_h

    panel_height = 3.0
    full_width   = panel_height * aspect_full
    crop_width   = panel_height * aspect_crop

    fig_width  = full_width + crop_width * n_panels + 0.4 * (n_panels + 1)
    fig_height = panel_height + 1.0  # extra for labels

    fig = plt.figure(figsize=(fig_width, fig_height))

    width_ratios = [full_width] + [crop_width] * n_panels
    gs = fig.add_gridspec(1, 1 + n_panels, width_ratios=width_ratios,
                          left=0.01, right=0.99, top=0.82, bottom=0.02,
                          wspace=0.04)

    # Full image axes
    ax_full = fig.add_subplot(gs[0, 0])
    ax_full.imshow(full_img)
    ax_full.axis('off')

    # Red rectangle on full image
    left, top, right, bottom = crop
    rect = mpatches.Rectangle(
        (left, top), right - left, bottom - top,
        linewidth=2, edgecolor='red', facecolor='none'
    )
    ax_full.add_patch(rect)

    # Crop panel axes
    ax_crops = []
    for i, (model_name, crop_path) in enumerate(panels):
        ax = fig.add_subplot(gs[0, i + 1])
        crop_img = np.array(Image.open(crop_path))
        ax.imshow(crop_img)
        ax.axis('off')

        label = LABEL_MAP.get(model_name, model_name)
        if model_name in metrics:
            psnr, ssim = metrics[model_name]
            subtitle = '{:.2f} dB / {:.4f}'.format(psnr, ssim)
        elif model_name == 'original':
            subtitle = '(original)'
        else:
            subtitle = ''

        ax.set_title('{}\n{}'.format(label, subtitle), fontsize=8,
                     pad=4, color='black')
        ax_crops.append(ax)

    # Connecting lines from red rectangle to first crop panel
    # Top-right corner of rectangle -> top-left of first crop
    # Bottom-right corner of rectangle -> bottom-left of first crop
    for y_rect, y_ax in [(top, 0.0), (bottom, 1.0)]:
        con = ConnectionPatch(
            xyA=(right, y_rect), coordsA=ax_full.transData,
            xyB=(0.0, 1.0 - y_ax), coordsB=ax_crops[0].transAxes,
            color='red', linewidth=1.2, zorder=5
        )
        fig.add_artist(con)

    out_path = os.path.join(folder, '{}_figure.png'.format(scale_name))
    plt.savefig(out_path, dpi=args.dpi, bbox_inches='tight')
    plt.close()
    print('Figure saved to {}'.format(out_path))
